// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file demo.colf.

/**
 * Package demo offers a demonstration.
 * These comment lines will end up in the generated code.
 */
package demo;
