// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file demo.colf for package demo.

#ifndef COLFER_H
#define COLFER_H

#include <limits.h>
#include <stdint.h>
#include <string.h>

#if CHAR_BIT != 8
#error "octet byte size"
#endif

#ifdef __cplusplus
extern "C" {
#endif


// colfer_size_max is the upper limit for serial octet sizes.
extern size_t colfer_size_max;

// colfer_list_max is the upper limit for the number of elements in a list.
extern size_t colfer_list_max;


// colfer_text is a UTF-8 CLOB.
typedef struct {
	const char*  utf8;
	size_t       len;
} colfer_text;

// colfer_binary is a BLOB.
typedef struct {
	uint8_t* octets;
	size_t   len;
} colfer_binary;


typedef struct demo_message demo_message;


// A message and its contents. :)
struct demo_message {

	colfer_text contents;
};

// demo_message_marshal_len returns the Colfer serial octet size.
// When the return is zero then errno is set to EFBIG to indicate a breach of
// either colfer_size_max or colfer_list_max.
size_t demo_message_marshal_len(const demo_message* o);

// demo_message_marshal encodes o as Colfer into buf and returns the number
// of octets written.
size_t demo_message_marshal(const demo_message* o, void* buf);

// demo_message_unmarshal decodes data as Colfer into o and returns the
// number of octets read. The data is read up to a maximum of datalen or
// colfer_size_max, whichever occurs first.
// When the return is zero then errno is set to one of the following 3 values:
// EWOULDBLOCK on incomplete data, EFBIG on a breach of either colfer_size_max
// or colfer_list_max and EILSEQ on schema mismatch.
size_t demo_message_unmarshal(demo_message* o, const void* data, size_t datalen);


#ifdef __cplusplus
} // extern "C"
#endif

#endif
