// Code generated by colf(1); DO NOT EDIT.
// The compiler used schema file demo.colf and GamePadReading.colf.

/**
 * These comment lines will end up in the generated code.
 */
package io.github.kitswas.VGP_Data_Exchange;
